### ISSUE TITLE
Bug with translations

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#145]
After changing the language type in the settings and restarting the server, the plugin continues to use the default language (US).

config.properties:

```properties
#BuycraftX configuration file
#Sat Sep 21 12:02:31 EDT 2019
server-key=
push-commands=true
disable-buy-command=true
verbose=false
check-for-updates=false
is-bungeecord=false
buy-command-name=vip
language=pt_BR
```

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
