### ISSUE TITLE
DonationReceiveEvent addition

### ISSUE THREAD

**Issue by LogGits** [BuycraftPlugin/BuycraftX#149]
Can you add a **DonationReceiveEvent** to that api that has in it:
- isGift() - self explanatory
- getBuyerPlatform() - What the user used to purchase the items on (e.g. Mobile, Browser, tablet, etc)
- getUsername() - Minecraft username of who donated (or was gifted)
- getPurchasedItemName() - the name of what they purchased.
- getPurchasedItemPrice() - how much it was purchased for.
- getBuyerIP() - returns the ip of the buyer (allows for developer checks)
- getDiscount() - get the amount that was discounted.
- getPurchaseTime() - get the time of purchase.

This would make it super convenient to expand making custom, unique and cool stuff for servers. 
Thanks a tonne.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to provide this suggestion, I'm sorry it's been slow to reply to your idea — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and I will happily note this idea down for the recode.

Thanks for providing a cool suggestion :)

**Comment by entity** [comment]
Hi there,

Thank you for taking the time to suggest this idea. We appreciate your input and would like to let you know that we have now added this suggestion to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your suggestion in mind as we work on this update and will consider implementing it if it fits with our development roadmap.

Since we have now noted your suggestion in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for your suggestion and for your continued support of Tebex.

Best regards,
The Integrations Team.
