### ISSUE TITLE
Feature Request: allow setting coupon code from the Buycraft command 

### ISSUE THREAD

**Issue by Towerism** [BuycraftPlugin/BuycraftX#160]

**Comment by heychazza** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to provide this suggestion, I'm sorry it's been slow to reply to your idea — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and I will happily note this idea down for the recode.

Thanks for providing a cool suggestion :)

**Comment by entity** [comment]
Hi there,

Thank you for taking the time to suggest this idea. We appreciate your input and would like to let you know that we have now added this suggestion to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your suggestion in mind as we work on this update and will consider implementing it if it fits with our development roadmap.

Since we have now noted your suggestion in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for your suggestion and for your continued support of Tebex.

Best regards,
The Integrations Team.
