### ISSUE TITLE
Could not fetch due players queue

### ISSUE THREAD

**Issue by fellettigiacomo** [BuycraftPlugin/BuycraftX#161]
Hi! I get this error in console.
[14:36:15 ERROR]: [BuycraftX] Could not fetch due players queue
java.net.SocketTimeoutException: timeout

Here's the full detailed error
https://pastebin.com/gfwp2Q6F

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
