### ISSUE TITLE
When payment commands (with push commands also) don't works

### ISSUE THREAD

**Issue by sergusson** [BuycraftPlugin/BuycraftX#162]
I have a network and i had some payments and i haved to make it in the server with commands manually, because the commands are not executed, i have push commands, verification secret key, all firewall ports enabled to the 2 ips of buycraft, all comands good configurated, i dont understand what is happening please help.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
