### ISSUE TITLE
Sign Listeners causing console errors with non-player sign removals

### ISSUE THREAD

**Issue by KeenbeanDJ** [BuycraftPlugin/BuycraftX#163]
I noticed an error that would seemingly occur when signs are removed via /setblock (setting to air), and it traced back to "onBlockBreak" listeners inside of the BuyNowSignListener and RecentPurchaseSignListener classes. I also tested this with a creeper explosion around several signs which repeated the same errors. 

From what I can gather, it appears to require a player optional to be present in order to process the innermost IF loop, despite the "onSignChange" methods above containing a check for non-player/non-sign events, as follows: https://github.com/tebexio/BuycraftX/blob/e6f87549e04fc65112767ee60a316937257b0e84/sponge/src/main/java/net/buycraft/plugin/sponge/signs/purchases/RecentPurchaseSignListener.java#L43-L48

Because it requires a player optional to pass through to the "removeSign" method, events processed through command blocks, entity griefing or other non-player sources of block breaking will cause it to return java.util.NoSuchElementException, due to not obtaining the required player optional. The onBlockBreak listeners referenced here in the error log, both referencing the innermost if statement (removeSign method):
https://github.com/tebexio/BuycraftX/blob/e6f87549e04fc65112767ee60a316937257b0e84/sponge/src/main/java/net/buycraft/plugin/sponge/signs/purchases/RecentPurchaseSignListener.java#L104-L114

https://github.com/tebexio/BuycraftX/blob/e6f87549e04fc65112767ee60a316937257b0e84/sponge/src/main/java/net/buycraft/plugin/sponge/signs/buynow/BuyNowSignListener.java#L113-L123

It appears to pass through both listeners and cause errors from both in the console for each sign removed.

Pastebin Log: https://mcpaste.io/0f33672bbbae3111

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
