### ISSUE TITLE
Error enabling plugin BuycraftX

### ISSUE THREAD

**Issue by donvdp** [BuycraftPlugin/BuycraftX#168]
BuyCraftX 12.0.6 wont startup with waterfall version 381 (lates)

console error:
https://pastebin.pl/view/cb84b53d

Running bungeecord "waterfall" build #381
https://papermc.io/downloads#Waterfall

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
