### ISSUE TITLE
Pre-1.13 items don't format properly

### ISSUE THREAD

**Issue by BomBardyGamer** [BuycraftPlugin/BuycraftX#172]
Using the Bukkit plugin, if you select an item on the web store, it will fail to parse that item as a valid item, and I can see why.

The logic you have written splits the material with a `:` to separate the left part as the material and the right as the variant. Only one problem: I believe that, when you browse for a certain item, it's setting the item's text to `minecraft:material`, which is then being split, and it tries to format `material` into a `short` which, as you know, doesn't work, and you end up with a `NumberFormatException`. Reproducible on Paper 1.12.2 (build 1618).

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
