### ISSUE TITLE
/buy command does not exist for commands.yml

### ISSUE THREAD

**Issue by lcbrakel** [BuycraftPlugin/BuycraftX#177]
When i want to make a new command for /buy to /ranks in command.yml it does not work it just gives me a standard error for a not existing command. I want to change this because when i use /buy it is red and i think it's ugly.

This is the command.yml file:
https://pastebin.com/JSYCSmj8

**Comment by detobel36** [comment]
It is normal because you can configure this command in the configuration
```YAML
buy-command-name: buy
```

So if you want that the command `/rank` do the same thing that the `/buy`, just change it in the configuration

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
