### ISSUE TITLE
Console Spam "Fetching for due players"

### ISSUE THREAD

**Issue by bl1u** [BuycraftPlugin/BuycraftX#181]
The console tends to quite frequently fetch for due players every couple minutes. There should be a way to hide console spam in the config file, so I don't need to refer to the logs file when on the server panel.

**Comment by melluh** [comment]
Setting verbose=false in the config.properties file fixes this.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
