### ISSUE TITLE
BuyCraftX Abandoned Basket Recovery Bug.

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#187]
BuyCraftX is still shooting Game Server Commands when field is not selected, yet command exists inside field.
https://i.imgur.com/2MTtVZL.png

I have left my command in the field so I don’t forget what it is when I do enable it in the future.
This is incorrect functionality.

Paper 1.17.1 Build 334
BuyCraftX compiled on https://github.com/tebexio/BuycraftX/commit/4c2cdb00d114f8afdac306a7bff2308c6beebbf1

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!

**Comment by andrewkm** [comment]
Still an issue.
