### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by cutover** [BuycraftPlugin/BuycraftX#192]
**When velocity starts up, the following error occurs:**

[03:23:29 ERROR]: Couldn't pass ProxyInitializeEvent to buycraft... 
https://pastebin.com/XSpsMDFG

**When Tebex tries to dispatch a command, the following error occurs:**

[03:31:31 ERROR]: Exception in task net.buycraft.plugin.execution.strategy.QueuedCommandExecutor@41ba23f4 by plugin BuycraftX...
https://pastebin.com/Pe755NuM

Velocity Version: velocity-3.1.1-98.jar
Tebex Velocity Version: buycraftx-velocity-12.0.8.jar

**Comment by PatchedNotFixed** [comment]
We are also getting this issue.

`java.lang.NoClassDefFoundError: net/kyori/text/Component`

https://pastebin.com/UEba8MFK

same as above
velocity-3.1.1-98.jar
buycraftx-velocity-12.0.8.jar

**Comment by Gamer153** [comment]
As it doesn't look like tebex cares about this at all, I've fixed the bugs with velocity and made an **unofficial** release for everyone stuggling with this: https://github.com/Gamer153/BuycraftX/releases/tag/v12.1.0
This should be 100 % compatible with existing installations.
If you don't trust me, you can look at the changes in the repo and then build it yourself by cloning the repo and running `mvn package`.
@KugelblitzNinja @JackGamer180

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

If your issue still exists, please reply here and I'll look into getting them fixed.

Apologies for the issues you have faced!

**Comment by entity** [comment]
Hi there,

Thank you again for taking the time to report this bug. We appreciate your input and would like to let you know that we have now added this bug to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your bug in mind as we work on this update and will note it in our development roadmap.

Since we have now noted your bug in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for reporting this bug and for your continued support of Tebex.

Best regards,
The Integrations Team.
