### ISSUE TITLE
Console Bug

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#199]
[11:56:53 WARN]: [BuycraftX] Plugin BuycraftX v12.0.8 generated an exception while executing task 4455071
net.buycraft.plugin.BuyCraftAPIException: That is not a valid username
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:71) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[BuycraftX.jar:?]

**Comment by xism4** [comment]
> [11:56:53 WARN]: [BuycraftX] Plugin BuycraftX v12.0.8 generated an exception while executing task 4455071 net.buycraft.plugin.BuyCraftAPIException: That is not a valid username at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:71) ~[BuycraftX.jar:?] at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?] at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?] at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[BuycraftX.jar:?]

Seems that the player wasn't proper handled by the plugin, may need a check before trying the thingy

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

If your issue still exists, please reply here and I'll look into getting them fixed.

Apologies for the issues you have faced!

**Comment by entity** [comment]
Hi again,

I'm just following up to let you know that we have now added this bug to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your bug in mind as we work on this update and will note it in our development roadmap.

Since we have now noted your bug in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for reporting this bug and for your continued support of Tebex.

Best regards,
The Integrations Team.
