### ISSUE TITLE
[Feature Request] Add Folia from PaperMC

### ISSUE THREAD

**Issue by Aitooor** [BuycraftPlugin/BuycraftX#203]
Will it possible to add Folia support?

Folia url: https://github.com/PaperMC/Folia

**Comment by entity** [comment]
Hey buddy,

Thanks for the suggestion regarding Folia - it’s certainly on our radar to look into once Folia is more stable. We have added your suggestion to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin shortly. We will keep your suggestion in mind as we work on this update and will note it in our development roadmap.

Since we have now noted your suggestion in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for your valuable suggestion and for your continued support of Tebex.

Best regards,
The Integrations Team.
