### ISSUE TITLE
Handle Buycraft being offline better

### ISSUE THREAD

**Issue by Puremin0rez** [BuycraftPlugin/BuycraftX#32]
As of writing, Buycraft is currently suffering some downtime.

During this downtime, restarting the server results in BuycraftX waiting a fairly long time to try to verify the server key, then waits a fairly long time once again to grab server packages after trying to verify the secret key. This for me took around a minute or so for BuycraftX to abort and let the server continue.

Once started, whenever BuycraftX attempts to retrieve information from the Buycraft service, a large stacktrace indicating a timeout is printed to console. This should probably be turned into a "Service unavailable" message and look much friendlier then a stacktrace.

http://pastebin.com/raw/uQRSDxvL

**Comment by minecrafter** [comment]
The newest versions already respect a much shorter timeout instead of waiting a minute. We will look at scrubbing exceptions from console output at a later date.

BuycraftX actually handles downtime _better_ than the old plugin, which would choke and frequently require a server restart to make it work. That being said, its logic could be improved and this is something we'll investigate.
